name: JAWP
version: 1.0.0
author: jf908
main: net.xyfe.spigot.jawp.JAWP
commands:
  warp:
    description: Teleport to a warp
    usage: /warp <name>
  warps:
    description: Lists all the existing warps
    usage: /warps
  setwarp:
    description: Creates a new warp
    usage: /setwarp <name>
  delwarp:
    description: Deletes a warp
    usage: /delwarp <name>
permissions:
  jawp.command.warp:
    description: Allows you to teleport to warps
    default: true
  jawp.command.warps:
    description: Allows you to list warps
    default: true
  jawp.command.setwarp:
    description: Allows you to set new warps
    default: op
  jawp.command.delwarp:
    description: Allows you to delete warps
    default: op
